### PR TITLE
Add Slovensko Region for 6.2.0

### PR DESCRIPTION
**Pull request by jhrcek**
This change can be checked with my [staging deployment](https://janhrcek.cz/natural-strategy-setup/)

### CODE REVIEW

**Comment by triceo** [comment]
A nitpick:
"Tato strategie vyžaduje RoboZonky ve verzi 6.0.0 nebo pozdější."
This is not true with this most recent addition.

**Comment by jhrcek** [comment]
Are you ok with unconditional bump to 6.2.0? I'll fix it later today.

**Comment by triceo** [comment]
Yes, I am.

**Comment by jhrcek** [comment]
Fixed.

**Comment by triceo** [comment]
Thanks!

**Pull request merged**
