### PR TITLE
Update web configurator for 6.0.0

### PR DESCRIPTION
**Pull request by jhrcek**
Implement new conditions for 5.9.0
https://github.com/RoboZonky/natural-strategy-setup/issues/72

Fix a regression
https://github.com/RoboZonky/natural-strategy-setup/issues/73

Improve UX of adding conditions to filters
https://github.com/RoboZonky/natural-strategy-setup/issues/74

### CODE REVIEW

**Comment by triceo** [comment]
The way things are going now, it seems that the next version will be 6.0.0. Stay tuned, I should know that for certain very soon. 

(Depends on whether my opus magnum is feasible or not. :-))

**Comment by jhrcek** [comment]
Opus magnus? You sparked my curiosity :smile:

**Comment by triceo** [comment]
https://github.com/RoboZonky/robozonky/pull/538

I am attempting to put together CI that would:

- Build platform-dependent distribution including a minimalistic customized JRE on Linux, Mac and Windows.
- Take that distribution and create a self-contained platform-dependent installer that itself doesn't require a pre-installed JRE to run.
- Deploy all of that into Nexus and release it.
- All with a single pipeline.
- Entirely unattended.

End goal? Users don't need to find, download and install Java. RoboZonky brings its own. No matter which platform you're on. The holy grail.

This has been on my mind for months. I'm finally making progress. :-)

**Comment by triceo** [comment]
I have succeeded! The next stable will be 6.0.0.

**Comment by triceo** [comment]
The minimum required version of RoboZonky will also need to be bumped to 6.0.0.

**Comment by jhrcek** [comment]
> The minimum required version of RoboZonky will also need to be bumped to 6.0.0.

Should I include that change in this PR?

**Comment by triceo** [comment]
Please do, no need to overcomplicate things.

**Comment by jhrcek** [comment]
I included the "Tato strategie vyžaduje RoboZonky ve verzi 6.0.0 nebo pozdější." change in this PR. Please ignore the 5.9.0 in the branch name, which I don't know how to rename for given PR - except for closing it and reopening from different branch. As always you can check in my deployment https://janhrcek.cz/natural-strategy-setup/

**Pull request merged**
