### PR TITLE
Update web tool for RoboZonky 5.1.0

### PR DESCRIPTION
**Pull request by jhrcek**
The update brings:
- migration to elm 0.19
- removal of rating condition
- mobile confirmations now based on interest condition (no longer rating cond.)
- stricter interest condition form (only valid percentages allowed)
- added support for reservation system
- added support of Loan annuity and Revenue rate conditions
- portfolio structure pie chart replaced with horizontal bar chart
- amount condition can now be used for participation filtering too

@triceo There's been a lot of changes, there might be some hiccups. Please test my [deployment](https://janhrcek.cz/natural-strategy-setup/) and let me know if you find any issue.

### CODE REVIEW

**Comment by triceo** [comment]
Will do, thanks!

**Comment by jhrcek** [comment]
Some notes based  on face to face discussion
1. remove "Prevzit kontrolu" from reservation system (also remove link to wiki and replace with link to self-created docs in natural-strategy-setup)
2. Add (semi transparent) bar to the bar chart representing maximum
3. When participation / loan or participation is selected during condition creation, name the Amount condition "Puvodni vyse uveru". For loans just leave the current condition name "výše úvěru"

**Comment by jhrcek** [comment]
@triceo updated the PR resolving the 3 notes from the comment above above. Keeping "The other" changes locally and will release them when it becomes public (and when you send me the RoboZonky source with the changes so I can test it).

**Comment by triceo** [comment]
@jhrcek Already did about an hour ago.

**Comment by jhrcek** [comment]
Closing this PR as the changes were introduced in https://github.com/RoboZonky/robozonky.github.io/commit/26835709f60632c57434927f123a85d5ceb87cb6

**Pull request closed without merging**
